### ISSUE TITLE
Project seems no longer compiles on Xcode Version 15.0 beta 2 (15A5161b) and iOS 17 Simulator.

### ISSUE THREAD

**Issue by waelsaad** [git-shawn/QR-Pop#9]
Hi, really nice project however just hoping we can fix it to compile on iOS 17 simulator. Thanks.

**Comment by waelsaad** [comment]
I had to remove the Connections package.

**Comment by git-shawn** [comment]
Hey @waelsaad thank you for the heads up. I've noticed that issue with the Connections package too and am going to submit a PR to fix it soon. There's a new [CNContact.ID typealias](https://developer.apple.com/documentation/contacts/cncontact/id) in iOS 17 that is causing a conflict right now that shouldn't be too difficult to square away. Thanks again!

**Comment by waelsaad** [comment]
Thank you @git-shawn  also I don't understand why on iOS 17 simulator its producing a the following list of warnings:-

https://github.com/git-shawn/SwiftUI-ScanKit/issues/1 I only just noticed both libraries were created by you Shawn :)

**Comment by git-shawn** [comment]
Merged with main in latest commit
